### ISSUE TITLE
/collections route returns array

### ISSUE THREAD

**Issue by jisantuc** [stac-utils/stac-fastapi#108]
The `/collections` route according to the API spec returns an object with `collections` and `links` keys --

- [route](https://github.com/radiantearth/stac-api-spec/blob/master/ogcapi-features/openapi.yaml#L93-L106)
- [capital C collections](https://github.com/radiantearth/stac-api-spec/blob/master/ogcapi-features/openapi.yaml#L344-L364)
- [lowercase c collections](https://github.com/radiantearth/stac-api-spec/blob/master/ogcapi-features/openapi.yaml#L271-L282)

The deployed version of the API that I saw this on was based on [this branch](https://github.com/lossyrob/arturo-stac-api/tree/feature/rde%2Fpc-changes) so I don't know if this is also true on `master`. If not I won't be offended by a quick close.

**Comment by lossyrob** [comment]
This was fixed, but a regression that was introduced in a recent refactor.

The [response model](https://github.com/stac-utils/stac-fastapi/blob/master/stac_fastapi/api/stac_fastapi/api/app.py#L209) for the collections endpoint is `Collections`, which is the correct format; however, `all_collections` on the backends and the base class (https://github.com/stac-utils/stac-fastapi/blob/9ef8601a1dfbf69c7a634eb255af2d84327b6294/stac_fastapi/types/stac_fastapi/types/core.py#L384) return a list of TypeDict Collection objects.

This should instead construct a stac-pydantic `Collections` object or a TypedDict with the appropriate entries, and return with the appropriate links (see [the PC endpoint for reference](https://planetarycomputer.microsoft.com/api/stac/v1/collections))

This could either be solved by changing the all_collections signature and modifying the backend core clients, or translating the list of collections at the API level so that all backends use the same logic to construct the Collections response
