### ISSUE TITLE
PUT request for item doesn't update the geometry

### ISSUE THREAD

**Issue by waseem-aidash** [stac-utils/stac-fastapi#124]
I am running into this issue in updating existing items while making  PUT request  on /collections/{collectionId}/items

Found [this](https://github.com/stac-utils/stac-fastapi/blob/master/stac_fastapi_sqlalchemy/stac_fastapi/sqlalchemy/transactions.py#L57) in the code where we are dropping geometry before forming update query. Is this an expected behaviour as per STAC spec?

**Comment by geospatial-jeff** [comment]
Its done because sqlalchemy ORM doesn't like doing updates with a geoalchemy type (see TODO https://github.com/stac-utils/stac-fastapi/blob/master/stac_fastapi/sqlalchemy/stac_fastapi/sqlalchemy/transactions.py#L55).  I ended up dropping the geometry column because I didn't have time to figure out how to fix this and updating geometries wasn't in my immediate use case.

The spec doesn't say anything about now allowing the geometry to be updated.

**Comment by waseem-aidash** [comment]
I see. 
This functionality is useful when for some reason we have to update the existing STAC items in a catalog. For my usecase, I did this by deleting and re-inserting, but would be good to have this functionality. Do you have any potential solutions scoped out for this ? If yes, please share here, else I'll do some research at my end on how to support this.

**Comment by geospatial-jeff** [comment]
> For my usecase, I did this by deleting and re-inserting, but would be good to have this functionality.
This is a good workaround for now.

I'm currently in the process of refactoring the sqlalchemy model to support #58, will try to fix this problem while I'm doing this!
