### ISSUE TITLE
POST search with intersects containing GeometryCollection fails with 400

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-fastapi#187]
According to the STAC API spec, all GeoJSON shape types must be supported by intersects. GeometryCollection is explicity defined in the openapi spec as one of these. 

Running this search fails with a 400 error:

POST /search
```json
{"intersects": { "type": "GeometryCollection", "geometries": [{"type": "Point", "coordinates": [100.0, 0.0]}, {"type": "LineString", "coordinates": [[101.0, 0.0], [102.0, 1.0]]}]}}
```

**Comment by geospatial-jeff** [comment]
Thats interesting.  My interpretation of the spec was that the search endpoint should only accept geojson geometry types, not any of the geometry containers.  Here is the language in the stac api spec:

> Searches items by performing intersection between their geometry and provided GeoJSON geometry. All GeoJSON geometry types must be supported.

And the [GeoJSON spec](https://datatracker.ietf.org/doc/html/rfc7946#section-1) says that the valid geometry types are `Point`, `Line`, `Polygon`, `MultiPoint`, `MultiLine`, and `MultiPolygon`.  No mention of `GeometryCollection`.

Assuming that `GeometryCollection` is valid, I'm wondering what the expected behavior would be here.  Return STAC Items that intersect with all geometries in the collection?  Return items that intersect with any of the geometries?

**Comment by philvarner** [comment]
Your link to the GeoJSON spec has: `GeoJSON supports the following geometry types:
   Point, LineString, Polygon, MultiPoint, MultiLineString,
   MultiPolygon, and GeometryCollection. `

The semantics are intersection with any of the geometries in the geometry collection.

**Comment by geospatial-jeff** [comment]
wow I'm awful at reading 😆 

> The semantics are intersection with any of the geometries in the geometry collection.

👍

**Comment by geospatial-jeff** [comment]
Currently we aren't using the stac-pydantic search model (https://github.com/stac-utils/stac-fastapi/blob/master/stac_fastapi/types/stac_fastapi/types/search.py#L85-L86).  But it looks like we could be using it.
