### ISSUE TITLE
Enable mypy pre-commit hook

### ISSUE THREAD

**Issue by geospatial-jeff** [stac-utils/stac-fastapi#190]

**Comment by kylebarron** [comment]
In the past I've avoided putting mypy in pre commit hooks because mypy ideally needs to be able to follow imports, and thus needs to have the full Python environment of the code, including dependencies, when `mypy` is called. Right now I tend to run mypy as part of the test script, but if you had a better way that would be great.

**Comment by kylebarron** [comment]
As an example of this, right now `rio-tiler` (at commit https://github.com/cogeotiff/rio-tiler/commit/63ea80b27cbf3687bc6283f20219af93ffb44a89) runs mypy through pre commit, and CI is passing. But if you _first_ install the environment and _then_ run mypy, you get lots of errors. IMO it's relatively pointless to run mypy when it can't access dependencies.

```
virtualenv env
source ./env/bin/activate
pip install '.[dev]'
pip install mypy
./env/bin/mypy rio_tiler
# Found 26 errors in 5 files (checked 22 source files)
```
