### ISSUE TITLE
Async interface creates code duplication

### ISSUE THREAD

**Issue by rsmith013** [stac-utils/stac-fastapi#215]
Look at wrappers such as [https://pypi.org/project/make-it-sync/](https://pypi.org/project/make-it-sync/) which can make a sync interface from an async one. Then we only have one class with both interfaces.

can use `inspect.iscoroutinefunction()` as part of the `_create_endpoint` method.

**Comment by vincentsarago** [comment]
👍 a bit linked, in #193 I added a top level function to either create sync or async endpoint based on the function's type https://github.com/stac-utils/stac-fastapi/pull/193/files/256315c15850aeeb45d3b6a3768e772a4ac613db#diff-3f814cfc24182540359cf16e8a3cedff38803d2feb6e489f7fc83b2e46758287R100-R109

**Comment by geospatial-jeff** [comment]
I don't think mixing synchronous and async/await interfaces into the same one is a good idea.  FastAPI executes the code differently if the route handler is `async def` or `def`.  In the `async def` case it will execute all of the code in the main thread's event loop.  In the `def` case it will execute all of the code in background threads in order to avoid blocking the event loop.

If we take async/await code, wrap it in `make-it-sync`, and then call it through a `def` route handler our code will execute across many different event loops across many threads.  This entirely defeats the purpose of using async/await to begin with and will add a lot of resource overhead to the application (especially at scale) due to thread management.

The reverse is taking synchronous code, wrapping its execution in a thread (to avoid blocking event loop), and call it through a `async def` route handler.  If we were to consolidate both execution models under one interface I'd argue this is the way to do it, as this will behave almost identically to how FastAPI executes `def` route handlers.  The downside is that your code looks like async/await code but it execute like synchronous code, which may be confusing to the user.

I do agree there is a lot of code duplication due to maintaining both synchronous and async/await interfaces but I think its not an unreasonable about of duplication.  There are nice things that come out of maintaining multiple interfaces as well like `isinstance` checks which could probably be implemented better with some improvements to inheritance.

**Comment by rsmith013** [comment]
ok, then I guess it relies on test coverage to make sure that the two interfaces don't diverge.

**Comment by moradology** [comment]
Closing, as this seems to have been resolved for now
