### ISSUE TITLE
Generalize the item geometry type on the Sqlalchemy backend

### ISSUE THREAD

**Issue by yellowcap** [stac-utils/stac-fastapi#284]
## Problem
I ran into some trouble when ingesting STAC items that do not have a simple Polygon geometry through the sqlalchemy backend. 

The geometry field is [required to be a Polygon](https://github.com/stac-utils/stac-fastapi/blob/master/stac_fastapi/sqlalchemy/stac_fastapi/sqlalchemy/models/database.py#L67), although the STAC Item spec specifies the field as the more general [GeoJSON Geometry](https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#item-fields), which includes other types such as MultiPolygon.

## Example STAC Item with MultiPolygon
I came across this problem when trying to ingest STAC Item data from the [usgs-landsat public bucket](https://registry.opendata.aws/usgs-landsat/).

In this catalog, there are some items that have the MultiPolygon type. For instance, Landsat scenes at the edge of the WGS84 projection are split into two. Here is a link to an example:

s3://usgs-landsat/collection02/level-2/standard/etm/2021/092/013/LE07_L2SP_092013_20211007_20211104_02_T2/LE07_L2SP_092013_20211007_20211104_02_T2_SR_stac.json

## Proposed solution
I would like to propose to change the geometry field to MultiPolygon or even GeometryCollection. This would still be matching the STAC spec.

This would presumably require a change in the field definition, an additional migration, and maybe a data-migration if the field content needs to be altered after this change. For instance, converting existing Polygon data to MultiPolygon.

## Related
The change of the field type was previously proposed, but the PR was mixed with a few other changes that were unrelated, so I am opening the discussion again. See https://github.com/stac-utils/stac-fastapi/pull/184

**Comment by geospatial-jeff** [comment]
I agree that the geometry type used by sqlalchemy backend needs to better align with the spec.  `GeometryCollection` type would probably be best because it gives the most flexibility.  My one concern is I'm not sure if there are performance drawbacks to using a `GeometryCollection` type over a more explicit type like `MultiPolygon` or `Polygon` (currently); that might be worth exploring before we make a change.

For what its worth, stac-pydantic recently added support for specifying `GeometryCollection` in search requests (https://github.com/stac-utils/stac-pydantic/pull/102), this change will be shipped in the next stac-pydantic release.

**Comment by photonbit** [comment]
If I understood correctly the STAC spec and the geoalchemy2 code, the only correct way of implementing this would be to have a `geoalchemy2.types.Geometry` that defaults to `geometry_type='GEOMETRY'`. That Geometry can hold any of the seven valid types for `Geometry`.

If we chose `Polygon`, `MultiPolygon` or even `GeometryCollection`, the implementation will be offending the specification, so even if it is a performance detriment, a reference implementation should offer all the accepted types.

**Comment by geospatial-jeff** [comment]
Closed with #299
