### ISSUE TITLE
`POST collections/{collectionId}/items` should accept an ItemCollection

### ISSUE THREAD

**Issue by geospatial-jeff** [stac-utils/stac-fastapi#362]
Conversation started here: https://github.com/stac-utils/stac-fastapi/issues/196#issuecomment-1049992324.  Posting an ItemCollection to the item creation endpoint seems to be a better way to support bulk transactions through the API than the bulk-transactions extension.

**Comment by philvarner** [comment]
We should maintain the BulkTransactionsClient as a concept, through maybe change the signature of:

def bulk_item_insert(self, items: Items, **kwargs) -> str

to

def bulk_item_insert(self, item_collection: ItemCollection, **kwargs) -> str

or

def bulk_item_insert(self, items: [Item], **kwargs) -> str

to still allow bulk inserts to the datastore, since PG and ES both support that and it makes insert quite a lot faster by amortizing the connection overhead.

**Comment by philvarner** [comment]
I would be in favor of at least deprecating the bulk_items endpoint.

**Comment by jonhealy1** [comment]
It does seem more intuitive to just post a feature collection to the items endpoint

**Comment by philvarner** [comment]
Yes -- it makes GET .../items and POST .../items symmetrical, which means you could directly pull from one API and write to another without needing to do any transformation of the response->request body

**Comment by geospatial-jeff** [comment]
I believe this was fixed with #367
