### ISSUE TITLE
Bad chars in collection id with request create works, but not with delete

### ISSUE THREAD

**Issue by remicres** [stac-utils/stac-fastapi#462]
When creating a collection (**POST /collections**), one can pass bad chars in collection id, e.g. "Spot-6/7 catalog".
Once created, such collection cannot be removed using **DELETE /collections/{collection_id}**, because of the wrong char (in my example, the "/" char).

**Comment by gadomski** [comment]
This is a hard (possibly impossible) problem to entangle. Since the collection ID is used to build the URL, any collection ID with a `/` will make the resulting URL inherently ambiguous. There's stuff in FastAPI to [work with path parameters](https://fastapi.tiangolo.com/tutorial/path-params/#path-convertor), but if my understanding is correct, that's only usable if the path parameter is the last component of the URL. Note that this is just a problem with `/` -- other "non-slug" characters (e.g. spaces) are supported no problem.

There's some guidance in the [best practices around avoiding `/` and similar characters](https://github.com/radiantearth/stac-spec/blob/master/best-practices.md#item-ids), so I think it's resonable to close this as wonfix. Please reopen if you think that there's some more action that we could take.
