### ISSUE TITLE
How to disable the `Transaction` extension in the `pgstac` app?

### ISSUE THREAD

**Issue by jtherrmann** [stac-utils/stac-fastapi#492]
We're currently using the `pgstac` app provided [here](https://github.com/stac-utils/stac-fastapi/blob/master/stac_fastapi/pgstac/stac_fastapi/pgstac/app.py), but we'd like to disable the Transaction extension. We're reluctant to do all of the configuration of the app from scratch. Is there a way to simply disable the extension in the app after it's already been created?

**Comment by geospatial-jeff** [comment]
Hello @jtherrmann the only way of doing this currently is to configure the app from scratch, the library is designed to do this and we encourage users to configure their own instead of relying on the existing applications (they are really just examples).

That being said we could introduce an environment variable to the pgstac backend which optionally enables or disables the transactions extension, allowing the user to set this at deploy time.  This seems reasonable to me.

**Comment by jtherrmann** [comment]
Thanks for the reply @geospatial-jeff. We like the idea of using an environment variable, so I may open a PR to make that change, if that's alright?

**Comment by jtherrmann** [comment]
I opened https://github.com/stac-utils/stac-fastapi/pull/495 just to demonstrate the approach I was thinking of.
