### ISSUE TITLE
support custom data models

### ISSUE THREAD

**Issue by geospatial-jeff** [stac-utils/stac-fastapi#58]
Currently there is no good way to use a different data model than what is defined in `models/database.py`.  Currently this is difficult to change in a way that is sustainable long term, should be much easier once #57 is resolved.

**Comment by MatProv** [comment]
Thanks @geospatial-jeff for addressing this issue, it will have a great impact on the way we could extend the implementation with custom schemas. I was wondering if this issue is currently in your short term pipeline or not. There are some attributes which we would like to add to items via custom schemas and want to make sure that these attributes could be queryable. Also, I was wondering if it could be possible to search in the `properties` JSONB document for custom property, or it absolutely needs to be indexed in a different column (https://github.com/arturo-ai/arturo-stac-api/pull/70) for search purposes.

**Comment by geospatial-jeff** [comment]
Several of us jumped on a call to discuss this issue and this is what we came up with: https://github.com/stac-utils/stac-fastapi/wiki/Custom-Models

The short of it is to remove pydantic as the interface between the API layer and the backend clients.

**Comment by kylebarron** [comment]
No disagreement there; think it's a valid conclusion. Just wish Pydantic were flexible enough to handle this use case.
