### ISSUE TITLE
Examine if pr 442 introduces breaking changes

### ISSUE THREAD

**Issue by jonhealy1** [stac-utils/stac-fastapi#644]
Examine if merging pr [442](https://github.com/stac-utils/stac-fastapi/pull/442) introduces breaking changes. If so, these changes should necessitate a v3.0.0 release next. 

In the comments for this pr, @geospatial-jeff declares that his work introduces a breaking change, while @gadomski later puts forth the idea that it is not a breaking change and fine for a v2.5.0 release.

**Comment by vincentsarago** [comment]
I think some could argue that https://github.com/stac-utils/stac-fastapi/pull/442/files#diff-4f8c5fdc9b3cca78110705589c68a6df26ac7a9d66bd4af3108db5174fdfe49cR99 is a breaking change because we change the `type` of the `middlewares` attribute.

In practice, user can still pass `middlewares=[BrotliMiddleware]` or `middlewares=[Middleware(BrotliMiddleware)]`

**Comment by jonhealy1** [comment]
Closing this because we are merging #442 in v3.0.0 which is a major release
